### ISSUE TITLE
i get errors when compiling 

### ISSUE THREAD

**Issue by zerodevstuff** [hypno1337/among-us-cheat-hypnotic#2]
how do i compile im in visual studio i tried building as debug and release both didnt work x64 and x86 aswell but for release x86 i got the error cannot open file 'minhook.lib'

**Comment by hypno1337** [comment]
Include vc++ libraries and includes

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by zerodevstuff** [comment]
oh thats what i forgot thx
